local rfsuite=require("rfsuite")
local lcd=lcd
local floor,min,max=math.floor,math.min,math.max
local cos,sin,rad=math.cos,math.sin,math.rad
local tonumber,tostring,type=tonumber,tostring,type
local format=string.format
local u=rfsuite.widgets.dashboard.utils
local ho=u.getHeaderOptions()
local cm=u.themeColors()
local hl=u.standardHeaderLayout(ho)
local C={bg=lcd.RGB(42,42,42),line=lcd.RGB(104,75,119),edge=lcd.RGB(151,107,160),white=lcd.RGB(246,239,255),muted=lcd.RGB(190,166,199),gold=lcd.RGB(255,199,91),cyan=lcd.RGB(58,238,216),green=lcd.RGB(81,241,139),pink=lcd.RGB(255,78,203),violet=lcd.RGB(187,107,255)}
local function val(t,n,a) t=t or(rfsuite.tasks and rfsuite.tasks.telemetry) if not(t and t.getSensor) then return nil end local v=t.getSensor(n) if v~=nil then return tonumber(v) end if a then v=t.getSensor(a) if v~=nil then return tonumber(v) end end end
local function fmt(v,d,s) if v==nil then return "--" end return (d==1 and format("%.1f",v) or tostring(floor(v+0.5)))..(s or "") end
local function ft(n) return u.resolveFont(n,nil) end
local function tx(x,y,w,s,f,c,a) local z=ft(f) if type(z)~="number" then return end lcd.font(z) lcd.color(c) local tw=lcd.getTextSize(s) if a=="center" then x=x+(w-tw)/2 elseif a=="right" then x=x+w-tw end lcd.drawText(floor(x),floor(y),s) end
local function dia(x,y,r,c) lcd.color(c) lcd.drawLine(x,y-r,x+r,y) lcd.drawLine(x+r,y,x,y+r) lcd.drawLine(x,y+r,x-r,y) lcd.drawLine(x-r,y,x,y-r) end
local function card(x,y,w,h,t,v,c) lcd.color(C.bg) lcd.drawFilledRectangle(floor(x),floor(y),floor(w),floor(h)) lcd.color(C.edge) lcd.drawRectangle(floor(x),floor(y),floor(w),floor(h),1) lcd.color(c) lcd.drawFilledRectangle(floor(x),floor(y),3,floor(h)) dia(floor(x+11),floor(y+11),5,c) tx(x+20,y+7,w-28,t,"FONT_XXS",C.muted,"left") tx(x+12,y+31,w-24,v,"FONT_L",C.white,"left") end
local function head(x,y,w,h) lcd.color(C.bg) lcd.drawFilledRectangle(floor(x),floor(y),floor(w),floor(h)) tx(x,y+8,w,"ETHOS // ROTORFLIGHT   |   MWRC","FONT_L",C.gold,"center") end
local hb,last
local function hboxes() local t=0 if rfsuite and rfsuite.preferences and rfsuite.preferences.general then t=rfsuite.preferences.general.txbatt_type or 0 end if not hb or last~=t then hb=u.standardHeaderBoxes(i18n,cm,ho,t) for _,b in ipairs(hb) do b.bgcolor=C.bg if b.type=="image" then b.type="func" b.subtype="func" b.paint=head end end last=t end return hb end
local S={[0]="OFF",[1]="IDLE",[2]="SPOOL",[3]="RECOVERY",[4]="ACTIVE",[5]="THR OFF",[7]="AUTOROT",[101]="DISARMED"}
local function wake(b,t) local c=b._cache or{max=0} b._cache=c c.rpm=val(t,"rpm","headspeed") or 0 c.max=max(c.max or 0,c.rpm) c.thr=val(t,"throttle_percent","throttle") or 0 c.esc=val(t,"temp_esc","esc_temp") c.fuel=val(t,"smartfuel") c.amps=val(t,"current") c.bec=val(t,"bec_voltage","bec") c.link=val(t,"link","vfr") c.mah=val(t,"smartconsumption","consumption") local g=val(t,"governor") c.state=g and S[floor(g+0.5)] or "STATE --" local s=rfsuite and rfsuite.session local sec=s and s.timer and tonumber(s.timer.live) or 0 c.time=format("%02d:%02d",floor(sec/60),floor(sec%60)) return c end
local function paint(x,y,w,h,b,c) x,y=u.applyOffset(x,y,b) c=c or b._cache or{} lcd.color(C.bg) lcd.drawFilledRectangle(floor(x),floor(y),floor(w),floor(h)) tx(x+14,y+8,w*0.4,"ZAFIRA // FLIGHT","FONT_STD",C.gold,"left") tx(x+w*0.36,y+3,w*0.28,c.time or "00:00","FONT_XL",C.white,"center") tx(x+w-210,y+9,196,c.state or "STATE --","FONT_STD",C.green,"right") local by=y+44 local bh=h-56 local sw=floor(w*0.20) local lx=x+12 local rx=x+w-sw-12 local mx=lx+sw+12 local mw=w-sw*2-48 card(lx,by,sw,floor((bh-10)/2),"EMBER",fmt(c.esc,0," C"),C.green) card(lx,by+floor((bh-10)/2)+10,sw,floor((bh-10)/2),"THRUST",fmt(c.thr,0,"%"),C.cyan) lcd.color(C.bg) lcd.drawFilledRectangle(floor(mx),floor(by),floor(mw),floor(bh)) lcd.color(C.edge) lcd.drawRectangle(floor(mx),floor(by),floor(mw),floor(bh),1) local cx=mx+mw/2 local cy=by+bh*0.47 local r=min(mw,bh)*0.39 local p=max(0,min(1,(c.rpm or 0)/2500)) for i=0,22 do local a=rad(150+240*i/22) local r1=r*0.55 local r2=r*(0.88+0.07*sin(rad(i*9))) local x1=floor(cx+cos(a)*r1) local y1=floor(cy+sin(a)*r1) local x2=floor(cx+cos(a)*r2) local y2=floor(cy+sin(a)*r2) lcd.color(i/22<=p and(i%3==0 and C.gold or C.violet) or C.line) lcd.drawLine(x1,y1,x2,y2) if i/22<=p then dia(x2,y2,4,i%3==0 and C.gold or C.violet) end end dia(floor(cx),floor(cy),floor(r*0.50),C.gold) dia(floor(cx),floor(cy),floor(r*0.32),C.green) tx(cx-r,cy-52,r*2,fmt(c.rpm,0,""),"FONT_XXL",C.white,"center") tx(cx-r,cy+8,r*2,"HEADSPEED RPM","FONT_XS",C.muted,"center") tx(cx-r,cy+39,r*2,c.state or "STATE --","FONT_S",C.green,"center") for i=0,9 do dia(floor(mx+mw*0.18+i*mw*0.07),floor(by+bh-50),7,i<floor((c.fuel or 0)/10+0.5) and C.green or C.line) end tx(mx+16,by+bh-27,mw-32,"MAX "..fmt(c.max,0," RPM"),"FONT_XS",C.gold,"left") tx(mx+16,by+bh-27,mw-32,"FUEL "..fmt(c.fuel,0,"%"),"FONT_XS",C.green,"right") local ch=floor((bh-30)/4) card(rx,by,sw,ch,"CURRENT",fmt(c.amps,1," A"),C.pink) card(rx,by+ch+10,sw,ch,"BEC",fmt(c.bec,1," V"),C.cyan) card(rx,by+(ch+10)*2,sw,ch,"LINK",fmt(c.link,0,"%"),C.cyan) card(rx,by+(ch+10)*3,sw,ch,"CONSUMED",fmt(c.mah,0," mAh"),C.violet) end
local box
local function boxes() if not box then box={{col=1,row=1,colspan=12,rowspan=12,type="func",subtype="func",wakeup=wake,paint=paint,bgcolor="transparent"}} end return box end
return{layout={cols=12,rows=12,padding=0},boxes=boxes,header_boxes=hboxes,header_layout=hl,screenBorderStyle={enabled=false},scheduler={spread_scheduling=true,spread_scheduling_paint=false,spread_ratio=0.85}}
