local rfsuite=require("rfsuite")
local lcd=lcd
local floor=math.floor
local cos,sin,rad=math.cos,math.sin,math.rad
local tonumber,tostring,type=tonumber,tostring,type
local format=string.format
local utils=rfsuite.widgets.dashboard.utils
local headeropts=utils.getHeaderOptions()
local colorMode=utils.themeColors()
local header_layout=utils.standardHeaderLayout(headeropts)
local C={bg=lcd.RGB(42,42,42),panel=lcd.RGB(42,42,42),line=lcd.RGB(104,75,119),line2=lcd.RGB(151,107,160),white=lcd.RGB(246,239,255),muted=lcd.RGB(190,166,199),gold=lcd.RGB(255,199,91),cyan=lcd.RGB(58,238,216),green=lcd.RGB(81,241,139),pink=lcd.RGB(255,78,203),violet=lcd.RGB(187,107,255)}
local function stat(t,n,m,a) t=t or(rfsuite.tasks and rfsuite.tasks.telemetry) local s=t and t.sensorStats local d=s and s[n] local v=d and d[m] if v~=nil then return tonumber(v) end if a then d=s and s[a] v=d and d[m] if v~=nil then return tonumber(v) end end end
local function fmt(v,d,u) if v==nil then return "--" end local q=d==1 and format("%.1f",v) or d==2 and format("%.2f",v) or tostring(floor(v+0.5)) return q..(u or "") end
local function font(n) return utils.resolveFont(n,nil) end
local function text(x,y,w,s,f,c,a) local ft=font(f) if type(ft)~="number" then return end lcd.font(ft) lcd.color(c) local tw=lcd.getTextSize(s) local tx=x if a=="center" then tx=x+(w-tw)/2 elseif a=="right" then tx=x+w-tw end lcd.drawText(floor(tx),floor(y),s) end
local function diamond(cx,cy,r,c,c2) lcd.color(c) lcd.drawLine(cx,cy-r,cx+r,cy) lcd.drawLine(cx+r,cy,cx,cy+r) lcd.drawLine(cx,cy+r,cx-r,cy) lcd.drawLine(cx-r,cy,cx,cy-r) if c2 then local q=floor(r*0.55) lcd.color(c2) lcd.drawLine(cx,cy-q,cx+q,cy) lcd.drawLine(cx+q,cy,cx,cy+q) lcd.drawLine(cx,cy+q,cx-q,cy) lcd.drawLine(cx-q,cy,cx,cy-q) end end
local function card(x,y,w,h,title,value,c) lcd.color(C.panel) lcd.drawFilledRectangle(floor(x),floor(y),floor(w),floor(h)) lcd.color(C.line2) lcd.drawRectangle(floor(x),floor(y),floor(w),floor(h),1) diamond(floor(x+12),floor(y+12),6,c,C.white) text(x+24,y+7,w-34,title,"FONT_XXS",C.muted,"left") text(x+12,y+32,w-24,value,"FONT_L",C.white,"left") end
local function header(x,y,w,h) lcd.color(C.bg) lcd.drawFilledRectangle(floor(x),floor(y),floor(w),floor(h)) text(x,y+8,w,"ETHOS // ROTORFLIGHT   |   MWRC","FONT_L",C.gold,"center") end
local hb,last=nil,nil
local function header_boxes() local t=0 if rfsuite and rfsuite.preferences and rfsuite.preferences.general then t=rfsuite.preferences.general.txbatt_type or 0 end if not hb or last~=t then hb=utils.standardHeaderBoxes(i18n,colorMode,headeropts,t) for _,b in ipairs(hb) do b.bgcolor=C.bg if b.type=="image" then b.type="func" b.subtype="func" b.paint=header end end last=t end return hb end
local function wake(box,t) local c=box._cache or{} box._cache=c c.rpm=stat(t,"rpm","max","headspeed") c.esc=stat(t,"temp_esc","max","esc_temp") c.current=stat(t,"current","max") c.watts=stat(t,"watts","max") c.bec=stat(t,"bec_voltage","min","bec") c.link=stat(t,"link","min","vfr") c.fuel=stat(t,"smartfuel","min") c.consumed=stat(t,"smartconsumption","max","consumption") c.pack=stat(t,"voltage","min") local s=rfsuite and rfsuite.session local sec=s and s.timer and tonumber(s.timer.live) or 0 c.time=format("%02d:%02d",floor(sec/60),floor(sec%60)) c.state,c.color="FLIGHT CHRONICLE",C.green return c end
local function paint(x,y,w,h,box,c) x,y=utils.applyOffset(x,y,box) c=c or box._cache or{} lcd.color(C.bg) lcd.drawFilledRectangle(floor(x),floor(y),floor(w),floor(h)) text(x+14,y+8,w*0.5,"ZAFIRA // FLIGHT CHRONICLE","FONT_STD",C.gold,"left") text(x+w-240,y+8,226,c.state or "FLIGHT CHRONICLE","FONT_STD",c.color or C.green,"right") local cx=x+w*0.5 local top=y+46 local sealH=floor(h*0.25) lcd.color(C.panel) lcd.drawFilledRectangle(floor(x+14),floor(top),floor(w-28),sealH) lcd.color(C.line2) lcd.drawRectangle(floor(x+14),floor(top),floor(w-28),sealH,1) for i=0,7 do local a=rad(i*45-90) diamond(floor(cx+cos(a)*sealH*0.43),floor(top+sealH*0.5+sin(a)*sealH*0.32),floor(sealH*0.10),i%2==0 and C.cyan or C.pink,C.gold) end diamond(floor(cx),floor(top+sealH*0.5),floor(sealH*0.28),C.gold,C.green) text(cx-sealH,top+sealH*0.34,sealH*2,"NOMINAL","FONT_XL",C.white,"center") text(cx-sealH,top+sealH*0.67,sealH*2,"FLIGHT TIME "..(c.time or "00:00"),"FONT_XS",C.cyan,"center") local gridY=top+sealH+12 local gap=10 local cw=floor((w-28-gap*2)/3) local ch=floor((h-(gridY-y)-14-gap)/2) local cards={{"MAX HEADSPEED",fmt(c.rpm,0," RPM"),C.gold},{"MAX ESC TEMP",fmt(c.esc,0," C"),C.green},{"PEAK CURRENT",fmt(c.current,1," A"),C.pink},{"MIN BEC",fmt(c.bec,2," V"),C.cyan},{"MIN LINK",fmt(c.link,0,"%"),C.cyan},{"CONSUMED",fmt(c.consumed,0," mAh"),C.violet}} for i=1,#cards do local row=floor((i-1)/3) local col=(i-1)%3 card(x+14+col*(cw+gap),gridY+row*(ch+gap),cw,ch,cards[i][1],cards[i][2],cards[i][3]) end text(x+14,y+h-26,w-28,"FUEL "..fmt(c.fuel,0,"%").."   POWER "..fmt(c.watts,0," W").."   PACK "..fmt(c.pack,1," V"),"FONT_XS",C.green,"center") end
local box
local function boxes() if not box then box={{col=1,row=1,colspan=12,rowspan=12,type="func",subtype="func",wakeup=wake,paint=paint,bgcolor="transparent"}} end return box end
return{layout={cols=12,rows=12,padding=0},boxes=boxes,header_boxes=header_boxes,header_layout=header_layout,screenBorderStyle={enabled=false},scheduler={spread_scheduling=true,spread_scheduling_paint=false,spread_ratio=0.85}}
