local rfsuite=require("rfsuite")
local lcd=lcd
local floor,min,max=math.floor,math.min,math.max
local cos,sin,rad=math.cos,math.sin,math.rad
local tonumber,tostring,type=tonumber,tostring,type
local format=string.format
local utils=rfsuite.widgets.dashboard.utils
local headeropts=utils.getHeaderOptions()
local colorMode=utils.themeColors()
local header_layout=utils.standardHeaderLayout(headeropts)
local C={bg=lcd.RGB(42,42,42),panel=lcd.RGB(42,42,42),line=lcd.RGB(104,75,119),line2=lcd.RGB(151,107,160),white=lcd.RGB(246,239,255),muted=lcd.RGB(190,166,199),gold=lcd.RGB(255,199,91),cyan=lcd.RGB(58,238,216),green=lcd.RGB(81,241,139),pink=lcd.RGB(255,78,203),violet=lcd.RGB(187,107,255),red=lcd.RGB(255,88,110),amber=lcd.RGB(255,166,62)}
local SECTION="system/zafira"
local DEF={bec_min=6.5,bec_warn=7.0,esc_warn=110,esc_max=150,fuel_warn=25,link_warn=50}
local function pref(k) local s=rfsuite and rfsuite.session local p=s and s.modelPreferences and s.modelPreferences[SECTION] return (p and tonumber(p[k])) or DEF[k] end
local function sensor(t,n,a) t=t or(rfsuite.tasks and rfsuite.tasks.telemetry) if not(t and t.getSensor) then return nil end local v=t.getSensor(n) if v~=nil then return tonumber(v) end if a then v=t.getSensor(a) if v~=nil then return tonumber(v) end end end
local function fmt(v,d,u) if v==nil then return "--" end local q=d==1 and format("%.1f",v) or tostring(floor(v+0.5)) return q..(u or "") end
local function font(n) return utils.resolveFont(n,nil) end
local function text(x,y,w,s,f,c,a) local ft=font(f) if type(ft)~="number" then return end lcd.font(ft) lcd.color(c) local tw=lcd.getTextSize(s) local tx=x if a=="center" then tx=x+(w-tw)/2 elseif a=="right" then tx=x+w-tw end lcd.drawText(floor(tx),floor(y),s) end
local function diamond(cx,cy,r,c,c2) lcd.color(c) lcd.drawLine(cx,cy-r,cx+r,cy) lcd.drawLine(cx+r,cy,cx,cy+r) lcd.drawLine(cx,cy+r,cx-r,cy) lcd.drawLine(cx-r,cy,cx,cy-r) if c2 then local q=floor(r*0.55) lcd.color(c2) lcd.drawLine(cx,cy-q,cx+q,cy) lcd.drawLine(cx+q,cy,cx,cy+q) lcd.drawLine(cx,cy+q,cx-q,cy) lcd.drawLine(cx-q,cy,cx,cy-q) end end
local function panel(x,y,w,h,title,value,c,sub) lcd.color(C.panel) lcd.drawFilledRectangle(floor(x),floor(y),floor(w),floor(h)) lcd.color(C.line2) lcd.drawRectangle(floor(x),floor(y),floor(w),floor(h),1) lcd.color(c) lcd.drawFilledRectangle(floor(x),floor(y),3,floor(h)) diamond(floor(x+10),floor(y+10),5,c,C.line2) text(x+16,y+7,w-28,title,"FONT_XXS",C.muted,"left") text(x+12,y+30,w-24,value,"FONT_L",C.white,"left") text(x+12,y+h-22,w-24,sub,"FONT_XXS",C.muted,"left") end
local function header(x,y,w,h) lcd.color(C.bg) lcd.drawFilledRectangle(floor(x),floor(y),floor(w),floor(h)) local f=font("FONT_L") if type(f)~="number" then return end lcd.font(f) local a,b,c="ETHOS ","// ","ROTORFLIGHT" local wa,th=lcd.getTextSize(a) local wb=lcd.getTextSize(b) local wc=lcd.getTextSize(c) local wf=font("FONT_XS") local wm="MWRC" local ww,wh=0,0 if type(wf)=="number" then lcd.font(wf) ww,wh=lcd.getTextSize(wm) lcd.font(f) end local tw=wa+wb+wc local tx=floor(x+(w-tw-ww-14)/2) local ty=floor(y+(h-th)/2) lcd.color(C.gold) lcd.drawText(tx,ty,a) lcd.color(C.pink) lcd.drawText(tx+wa,ty,b) lcd.color(C.white) lcd.drawText(tx+wa+wb,ty,c) if ww>0 then local dx=tx+tw+6 lcd.color(C.line2) lcd.drawLine(dx,y+7,dx,y+h-7) lcd.font(wf) lcd.color(C.cyan) lcd.drawText(dx+7,floor(y+(h-wh)/2),wm) end end
local hb,last=nil,nil
local function header_boxes() local t=0 if rfsuite and rfsuite.preferences and rfsuite.preferences.general then t=rfsuite.preferences.general.txbatt_type or 0 end if not hb or last~=t then hb=utils.standardHeaderBoxes(i18n,colorMode,headeropts,t) for _,b in ipairs(hb) do b.bgcolor=C.bg if b.type=="image" then b.type="func" b.subtype="func" b.paint=header end end last=t end return hb end
local function wake(box,t) local c=box._cache or{} box._cache=c c.fuel=sensor(t,"smartfuel") c.bec=sensor(t,"bec_voltage","bec") c.esc=sensor(t,"temp_esc","esc_temp") c.link=sensor(t,"link","vfr") c.rate=sensor(t,"rate_profile") c.pid=sensor(t,"pid_profile") c.pack=sensor(t,"voltage") local count=0 if c.fuel and c.fuel<=pref("fuel_warn") then count=count+1 end if c.bec and c.bec<pref("bec_warn") then count=count+1 end if c.esc and c.esc>=pref("esc_warn") then count=count+1 end if c.link and c.link<pref("link_warn") then count=count+1 end if count==0 then c.state,c.color,c.sub="READY TO FLY",C.green,"JEWELS ALIGNED" else c.state,c.color,c.sub="REVIEW",C.amber,tostring(count).." ITEM"..(count==1 and "" or "S") end return c end
local function paint(x,y,w,h,box,c) x,y=utils.applyOffset(x,y,box) c=c or box._cache or{} lcd.color(C.bg) lcd.drawFilledRectangle(floor(x),floor(y),floor(w),floor(h)) text(x+14,y+8,w*0.5,"ZAFIRA // PRE-FLIGHT","FONT_STD",C.gold,"left") text(x+w-230,y+8,216,c.state or "READY TO FLY","FONT_STD",c.color or C.green,"right") local cx=x+w*0.5 local cy=y+h*0.48 local r=min(w,h)*0.20 for i=0,7 do local a=rad(i*45-90) local px=floor(cx+cos(a)*r*1.05) local py=floor(cy+sin(a)*r*1.05) diamond(px,py,floor(r*0.27),i%2==0 and C.cyan or C.pink,C.gold) end diamond(floor(cx),floor(cy),floor(r*0.72),C.gold,C.green) diamond(floor(cx),floor(cy),floor(r*0.42),c.color or C.green,C.white) text(cx-r,cy-46,r*2,c.state or "READY","FONT_XL",C.white,"center") text(cx-r,cy+10,r*2,c.sub or "JEWELS ALIGNED","FONT_XS",c.color or C.green,"center") text(cx-r,cy+42,r*2,"FUEL "..fmt(c.fuel,0,"%"),"FONT_S",C.green,"center") local nw=floor(w*0.21) local nh=floor(h*0.19) local lx=x+14 local rx=x+w-nw-14 local y1=y+54 local y2=y+h-nh-14 panel(lx,y1,nw,nh,"SAPPHIRE BEC",fmt(c.bec,1," V"),C.cyan,"POWER CLARITY") panel(lx,y2,nw,nh,"TURQUOISE LINK",fmt(c.link,0,"%"),C.cyan,"RADIO CLARITY") panel(rx,y1,nw,nh,"EMBER TEMP",fmt(c.esc,0," C"),C.green,"ESC THERMAL") panel(rx,y2,nw,nh,"FLIGHT JEWELS","R"..fmt(c.rate,0,"").." P"..fmt(c.pid,0,""),C.violet,"PACK "..fmt(c.pack,1," V")) end
local box
local function boxes() if not box then box={{col=1,row=1,colspan=12,rowspan=12,type="func",subtype="func",wakeup=wake,paint=paint,bgcolor="transparent"}} end return box end
return{layout={cols=12,rows=12,padding=0},boxes=boxes,header_boxes=header_boxes,header_layout=header_layout,screenBorderStyle={enabled=false},scheduler={spread_scheduling=true,spread_scheduling_paint=false,spread_ratio=0.85}}
