--[[
  Copyright (C) 2026 Rotorflight Project
  GPLv3 -- https://www.gnu.org/licenses/gpl-3.0.en.html
]] --

return {
    ["esc_signature"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.esc_signature)@",
    ["esc_command"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.esc_command)@",
    ["esc_type"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.esc_type)@",
    ["esc_model"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.esc_model)@",
    ["esc_sn"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.esc_sn)@",
    ["esc_iap"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.esc_iap)@",
    ["esc_fw"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.esc_fw)@",
    ["esc_hardware"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.esc_hardware)@",
    ["throttle_min"] = "Minimum throttle calibration value",
    ["throttle_max"] = "Maximum throttle calibration value",
    ["esc_mode"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.governor)@",
    ["cell_count"] = "Number of cells in the battery",
    ["low_voltage_protection"] = "Voltage at which we cut power by 50%",
    ["temperature_protection"] = "Temperature at which we cut power by 50%",
    ["bec_voltage"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.bec_voltage)@",
    ["electrical_angle"] = "Electrical angle for the motor",
    ["motor_direction"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.motor_direction)@",
    ["starting_torque"] = "Starting power for the motor",
    ["response_speed"] = "Response speed for the motor",
    ["buzzer_volume"] = "Beeper volume",
    ["current_gain"] = "Gain value for the current sensor",
    ["fan_control"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.fan_control)@",
    ["soft_start"] = "Soft start time",
    ["auto_restart_time"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.auto_restart_time)@",
    ["restart_acc"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.restart_acc)@",
    ["gov_p"] = "Proportional value for the governor",
    ["gov_i"] = "Integral value for the governor",
    ["active_freewheel"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.active_freewheel)@",
    ["drive_freq"] = "PWM drive frequency",
    ["motor_erpm_max"] = "Maximum motor electrical rpm",
    ["throttle_protocol"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.throttle_protocol)@",
    ["telemetry_protocol"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.telemetry_protocol)@",
    ["led_color_index"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.led_color_index)@",
    ["led_color_rgb"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.led_color_rgb)@",
    ["motor_temp_sensor"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.motor_temp_sensor)@",
    ["motor_temp"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.motor_temp)@",
    ["battery_capacity"] = "@i18n(api.ESC_PARAMETERS_FLYROTOR.battery_capacity)@",
}
