--[[
  Copyright (C) 2026 Rotorflight Project
  GPLv3 -- https://www.gnu.org/licenses/gpl-3.0.en.html
]] --

return {
    ["pid_mode"] = "@i18n(api.PID_PROFILE.pid_mode)@",
    ["error_decay_time_ground"] = "Bleeds off the current controller error when the craft is not airborne to stop the craft tipping over.",
    ["error_decay_time_cyclic"] = "Time constant for bleeding off cyclic I-term. Higher will stabilize hover, lower will drift.",
    ["error_decay_time_yaw"] = "@i18n(api.PID_PROFILE.error_decay_time_yaw)@",
    ["error_decay_limit_cyclic"] = "Maximum bleed-off speed for cyclic I-term.",
    ["error_decay_limit_yaw"] = "@i18n(api.PID_PROFILE.error_decay_limit_yaw)@",
    ["error_rotation"] = "Rotates the current roll and pitch error terms around yaw when the craft rotates. This is sometimes called Piro Compensation.",
    ["error_limit_0"] = "Hard limit for the angle error in the PID loop. The absolute error and thus the I-term will never go above these limits.",
    ["error_limit_1"] = "Hard limit for the angle error in the PID loop. The absolute error and thus the I-term will never go above these limits.",
    ["error_limit_2"] = "Hard limit for the angle error in the PID loop. The absolute error and thus the I-term will never go above these limits.",
    ["gyro_cutoff_0"] = "PID loop overall bandwidth in Hz.",
    ["gyro_cutoff_1"] = "PID loop overall bandwidth in Hz.",
    ["gyro_cutoff_2"] = "PID loop overall bandwidth in Hz.",
    ["dterm_cutoff_0"] = "D-term cutoff in Hz.",
    ["dterm_cutoff_1"] = "D-term cutoff in Hz.",
    ["dterm_cutoff_2"] = "D-term cutoff in Hz.",
    ["iterm_relax_type"] = "Choose the axes in which this is active. RP: Roll, Pitch. RPY: Roll, Pitch, Yaw.",
    ["iterm_relax_cutoff_0"] = "Helps reduce bounce back after fast stick movements. Can cause inconsistency in small stick movements if too low.",
    ["iterm_relax_cutoff_1"] = "Helps reduce bounce back after fast stick movements. Can cause inconsistency in small stick movements if too low.",
    ["iterm_relax_cutoff_2"] = "Helps reduce bounce back after fast stick movements. Can cause inconsistency in small stick movements if too low.",
    ["yaw_cw_stop_gain"] = "Stop gain (PD) for clockwise rotation.",
    ["yaw_ccw_stop_gain"] = "Stop gain (PD) for counter-clockwise rotation.",
    ["yaw_precomp_cutoff"] = "Frequency limit for all yaw precompensation actions.",
    ["yaw_cyclic_ff_gain"] = "Cyclic feedforward mixed into yaw (cyclic-to-yaw precomp).",
    ["yaw_collective_ff_gain"] = "Collective feedforward mixed into yaw (collective-to-yaw precomp).",
    ["yaw_collective_dynamic_gain"] = "An extra boost of yaw precomp on collective input.",
    ["yaw_collective_dynamic_decay"] = "Decay time for the extra yaw precomp on collective input.",
    ["pitch_collective_ff_gain"] = "Increasing will compensate for the pitching up motion caused by tail drag when climbing.",
    ["angle_level_strength"] = "Determines how aggressively the helicopter tilts back to level while in Angle Mode.",
    ["angle_level_limit"] = "Limit the maximum angle the helicopter will pitch/roll to while in Angle mode.",
    ["horizon_level_strength"] = "Determines how aggressively the helicopter tilts back to level while in Horizon Mode.",
    ["trainer_gain"] = "Determines how aggressively the helicopter tilts back to the maximum angle (if exceeded) while in Acro Trainer Mode.",
    ["trainer_angle_limit"] = "Limit the maximum angle the helicopter will pitch/roll to while in Acro Trainer Mode.",
    ["cyclic_cross_coupling_gain"] = "Amount of compensation applied for pitch-to-roll decoupling.",
    ["cyclic_cross_coupling_ratio"] = "Amount of roll-to-pitch compensation needed, vs. pitch-to-roll.",
    ["cyclic_cross_coupling_cutoff"] = "Frequency limit for the compensation. Higher value will make the compensation action faster.",
    ["offset_limit_0"] = "Hard limit for the High Speed Integral offset angle in the PID loop. The O-term will never go over these limits.",
    ["offset_limit_1"] = "Hard limit for the High Speed Integral offset angle in the PID loop. The O-term will never go over these limits.",
    ["bterm_cutoff_0"] = "B-term cutoff in Hz.",
    ["bterm_cutoff_1"] = "B-term cutoff in Hz.",
    ["bterm_cutoff_2"] = "B-term cutoff in Hz.",
    ["yaw_inertia_precomp_gain"] = "Scalar gain. The strength of the main rotor inertia. Higher value means more precomp is applied to yaw control.",
    ["yaw_inertia_precomp_cutoff"] = "Cutoff. Derivative cutoff frequency in 1/10Hz steps. Controls how sharp the precomp is. Higher value is sharper.",
}
