name: Snapshot

on:
  push:
    tags:
      - 'snapshot/*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # use the tag name (e.g. "snapshot/1.2.3") as GIT_VER
      GIT_VER: ${{ github.ref_name }}
      GIT_TAG: ${{ github.ref_name }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set build variables
        run: |
          echo "GIT_VER=${GIT_VER}" >> $GITHUB_ENV
          echo "GIT_TAG=${GIT_TAG}" >> $GITHUB_ENV
          cat $GITHUB_ENV

      - name: Make snapshot package
        run: |
          zip -q -r -9 "rotorflight-lua-ethos-suite-${{ env.GIT_VER }}.zip" scripts/rfsuite

      - name: Package combined soundpack
        run: |
          SOUND_DIR="bin/sound-generator/soundpack"
          OUTPUT_DIR="${GITHUB_WORKSPACE}/tmp"
          mkdir -p "$OUTPUT_DIR"

          ZIP_NAME="rotorflight-lua-ethos-suite-soundpack-${{ env.GIT_VER }}.zip"
          (cd "$SOUND_DIR" && zip -r "$OUTPUT_DIR/$ZIP_NAME" .)
          echo "✅ Created $OUTPUT_DIR/$ZIP_NAME"

      - name: Upload soundpack artifact
        uses: actions/upload-artifact@v4
        with:
          name: rotorflight-lua-ethos-suite-soundpack-${{ env.GIT_VER }}
          path: tmp/*.zip

      - name: Create Snapshot Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          .github/scripts/extract-release-notes.py "${{ env.GIT_VER }}" Releases.md > Notes.md
          gh release create "${{ env.GIT_TAG }}" \
            --prerelease \
            --notes-file Notes.md \
            --title "Rotorflight Lua Suite for Ethos - Snapshot ${{ env.GIT_VER }}" \
            rotorflight-lua-ethos-suite-${{ env.GIT_VER }}.zip \
            tmp/rotorflight-lua-ethos-suite-soundpack-${{ env.GIT_VER }}.zip
