name: Testing

on:
  push:
    tags:
      - 'testing/*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set build variables
      run: |
        echo "GIT_VER=${GITHUB_REF##*/}" >> ${GITHUB_ENV}
        echo "GIT_TAG=${GITHUB_REF##refs/tags/}" >> ${GITHUB_ENV}
        cat ${GITHUB_ENV}

    - name: Update version and config in main.lua
      run: |
        # Set version from tag
        sed -i "s/config.Version = \".*\"/config.Version = \"${{ env.GIT_VER }}\"/" scripts/rfsuite/main.lua

        # Set logging settings
        sed -i 's/config.logLevel= ".*"/config.logLevel= "off"/' scripts/rfsuite/main.lua
        sed -i 's/config.logToFile = .*/config.logToFile = false/' scripts/rfsuite/main.lua
        sed -i 's/config.logMSP = .*/config.logMSP = false/' scripts/rfsuite/main.lua

        # Show updated file (for verification)
        grep 'config\.' scripts/rfsuite/main.lua

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rotorflight-lua-ethos-suite-testing-${{ env.GIT_VER }}
        path: scripts

    - name: Delete tag
      run: git push origin :${GITHUB_REF}
